"""
Generates a Locust load-test file from the unified feature model.
Hits the backend endpoint DIRECTLY (bypasses the browser/UI entirely --
this was already the case, and remains so), and now generates a FRESH,
realistic payload per request using Faker (via generator/fake_data.py),
instead of replaying one static payload thousands of times.
"""
import json
import os

RESULTS_DIR = os.path.join(os.path.dirname(__file__), "..", "results")
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "tests_generated")


def gen(case: str):
    with open(os.path.join(RESULTS_DIR, f"feature_model_case{case}.json"), encoding="utf-8") as f:
        model = json.load(f)

    fields_literal = json.dumps(
        [{"name": f["name"], "type": f.get("type", "text")} for f in model["fields"]]
    )

    content = f'''"""AUTO-GENERATED by generator/gen_locustfile.py -- do not edit by hand.

Bypasses the UI entirely: POSTs straight to the backend form endpoint
({model['submit_endpoint']}), generating a fresh realistic payload per
request via Faker so load patterns look like real concurrent users
rather than one replayed payload.
"""
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "generator"))
from fake_data import fake_value_for  # noqa: E402

from locust import HttpUser, task, between

FIELDS = {fields_literal}


class FormUser(HttpUser):
    wait_time = between(0.5, 1.5)
    host = "http://127.0.0.1:5000"

    @task
    def submit_form(self):
        payload = {{f["name"]: fake_value_for(f["name"], f["type"]) for f in FIELDS}}
        self.client.post("{model['submit_endpoint']}", data=payload)
'''
    out_path = os.path.join(OUT_DIR, "locustfile.py")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"Generated Locust file (Faker-driven, direct endpoint) -> {out_path}")


if __name__ == "__main__":
    import sys
    gen(sys.argv[1] if len(sys.argv) > 1 else "A")
