"""
Generates a Playwright functional test file from the unified feature model.
Produces one positive (valid submission) test and, per field, a negative
test using a boundary/invalid value -- classic equivalence-partition style
test-case generation driven entirely by the extracted feature model.
"""
import json
import os

RESULTS_DIR = os.path.join(os.path.dirname(__file__), "..", "results")
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "tests_generated")

# Per-FIELD-NAME defaults (not per-type) so values are semantically valid
# for that specific field (e.g. "phone" must satisfy its own pattern, not
# just be a generic "text" string).
VALID_VALUES_BY_NAME = {
    "full_name": "Jane Doe",
    "email": "jane.doe@example.com",
    "age": "25",
    "password": "SecurePass1",
    "phone": "9876543210",
}
VALID_VALUES = {  # fallback by type, for fields not in the by-name map
    "text": "Jane Doe",
    "email": "jane.doe@example.com",
    "number": "25",
    "password": "SecurePass1",
}

INVALID_VALUES = {
    "text": "",
    "email": "not-an-email",
    # A native <input type="number"> element refuses non-numeric keystrokes
    # entirely (Playwright's .fill() can't type "abc" into it), so use a
    # numeric value that is still invalid per the backend's range rule.
    "number": "5",
    "password": "short",
}


def valid_for(field):
    return VALID_VALUES_BY_NAME.get(field["name"], VALID_VALUES.get(field["type"], "test"))


def gen(case: str):
    with open(os.path.join(RESULTS_DIR, f"feature_model_case{case}.json"), encoding="utf-8") as f:
        model = json.load(f)

    lines = [
        '"""AUTO-GENERATED by generator/gen_playwright.py -- do not edit by hand."""',
        "import json",
        "import os",
        "from playwright.sync_api import sync_playwright",
        "",
        f'URL = "http://127.0.0.1:5000/"',
        'SCREENSHOT_DIR = os.path.join("..", "results", "screenshots")',
        "os.makedirs(SCREENSHOT_DIR, exist_ok=True)",
        "results = []",
        "",
        "def record(name, passed, detail='', screenshot=None):",
        "    results.append({'test': name, 'passed': passed, 'detail': detail, 'screenshot': screenshot})",
        "",
        "def snap(page, name):",
        "    \"\"\"Capture a screenshot on failure -- gives a test-level drill-down",
        "    artifact instead of just a pass/fail line, the way Playwright's own",
        "    HTML reporter and most CI dashboards do.\"\"\"",
        "    path = os.path.join(SCREENSHOT_DIR, f'{name}.png')",
        "    try:",
        "        page.screenshot(path=path)",
        "        return f'results/screenshots/{name}.png'",
        "    except Exception:",
        "        return None",
        "",
        "def run():",
        "    with sync_playwright() as p:",
        '        browser = p.chromium.launch(channel="chrome", headless=True)',
        "        page = browser.new_page()",
        "",
        "        # --- Positive case: all valid values ---",
        "        page.goto(URL)",
        # Disable native HTML5 constraint validation so every submission is
        # actually round-tripped to the server -- we want to test the
        # BACKEND's validation, not the browser's.
        '        page.evaluate("document.querySelector(\'form\').noValidate = true")',
    ]

    for field in model["fields"]:
        val = valid_for(field)
        lines.append(f'        page.fill("input[name=\'{field["name"]}\']", "{val}")')
    lines += [
        '        page.click("button[type=\'submit\']")',
        '        page.wait_for_selector("#result .ok, #result .err", timeout=5000)',
        '        ok = page.query_selector("#result .ok") is not None',
        '        record("positive_all_valid", ok, screenshot=(None if ok else snap(page, "positive_all_valid")))',
        "",
        "        # --- Negative cases: one invalid field at a time ---",
    ]

    for field in model["fields"]:
        if not field.get("required"):
            continue
        invalid_val = INVALID_VALUES.get(field["type"], "")
        lines.append(f'        page.goto(URL)')
        lines.append('        page.evaluate("document.querySelector(\'form\').noValidate = true")')
        for other in model["fields"]:
            val = invalid_val if other["name"] == field["name"] else valid_for(other)
            lines.append(f'        page.fill("input[name=\'{other["name"]}\']", "{val}")')
        lines += [
            '        page.click("button[type=\'submit\']")',
            '        page.wait_for_selector("#result .ok, #result .err", timeout=5000)',
            '        rejected = page.query_selector("#result .err") is not None',
            f'        name = "negative_{field["name"]}_invalid"',
            '        record(name, rejected, screenshot=(None if rejected else snap(page, name)))',
            "",
        ]


    lines += [
        "        browser.close()",
        "",
        '    with open("../results/playwright_results.json", "w", encoding="utf-8") as f:',
        "        json.dump(results, f, indent=2)",
        '    print(f"Playwright: {sum(r[\'passed\'] for r in results)}/{len(results)} passed")',
        "",
        'if __name__ == "__main__":',
        "    run()",
    ]

    out_path = os.path.join(OUT_DIR, "test_functional.py")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Generated Playwright test -> {out_path}")


if __name__ == "__main__":
    import sys
    gen(sys.argv[1] if len(sys.argv) > 1 else "A")
