"""
Generates a comprehensive Pytest unit/contract test suite from the unified feature model.

Features:
- Plain-English Test Suite Cataloging:
    * Every test has a rich docstring declaring intent, rule origin, target form fields, and expected outcome.
    * Every test carries the custom marker @pytest.mark.description(...) with structured metadata:
      (intent=..., fields=[...], expected=...) directly in code.
- Case A (SRS Document / Specification Provided):
    * Tests assert against SRS specifications (required fields, boundaries, data types, lengths).
- Case B (No SRS Document Provided - Black Box):
    * Tests assert against black-box rules inferred from Accessibility Tree, DOM attributes, and probing.
"""
import json
import os

RESULTS_DIR = os.path.join(os.path.dirname(__file__), "..", "results")
OUT_DIR = os.path.join(os.path.dirname(__file__), "..", "tests_generated")


def gen(case: str = "A"):
    model_path = os.path.join(RESULTS_DIR, f"feature_model_case{case}.json")
    if not os.path.exists(model_path):
        raise FileNotFoundError(f"Feature model file not found: {model_path}")

    with open(model_path, encoding="utf-8") as f:
        model = json.load(f)

    import urllib.parse
    source_url = model.get("source_url", "http://127.0.0.1:5000/")
    endpoint = model.get("submit_endpoint", "/submit")
    full_url = urllib.parse.urljoin(source_url, endpoint)
    spec_source = model.get("specification_source", "Specification")

    method = model.get("method", "POST").upper()
    req_call = f"session.post(URL, data=payload, timeout=10, allow_redirects=True)" if method == "POST" else f"session.get(URL, params=payload, timeout=10, allow_redirects=True)"
    req_valid_call = f"session.post(URL, data=VALID_PAYLOAD, timeout=10, allow_redirects=True)" if method == "POST" else f"session.get(URL, params=VALID_PAYLOAD, timeout=10, allow_redirects=True)"

    header = f'''"""AUTO-GENERATED by generator/gen_pytest.py -- do not edit by hand.
Phase 1: Unit Testing using Pytest.
Specification Mode: Case {case} ({spec_source}).
Target URL: {full_url}
Method: {method}
"""
import pytest
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

URL = "{full_url}"
session = requests.Session()
session.headers.update({{"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"}})
_adapter = HTTPAdapter(max_retries=Retry(total=3, backoff_factor=0.5, status_forcelist=[500, 502, 503, 504]))
session.mount("https://", _adapter)
session.mount("http://", _adapter)

VALID_PAYLOAD = {{
'''
    valid_defaults = {
        "full_name": "Jane Doe",
        "email": "jane.doe@example.com",
        "age": "25",
        "password": "SecurePass123",
        "phone": "9876543210",
        "address": "123 Main Street",
        "country": "IN",
        "state": "Kerala",
        "card_number": "4111111111111111",
        "coupon": "SAVE20",
    }

    def infer_default_val(f):
        fname = f.get("name", "").lower()
        ftype = f.get("type", "text")
        if f.get("name") in valid_defaults:
            return valid_defaults[f["name"]]
        if "email" in fname or ftype == "email":
            return "jane.doe@example.com"
        if "pass" in fname or ftype == "password":
            return "SecurePass123"
        if "age" in fname or ftype == "number" or f.get("accessible_role") == "spinbutton":
            return "25"
        if "phone" in fname or "tel" in fname or ftype == "tel":
            return "9876543210"
        if "name" in fname or "user" in fname:
            return "JaneDoe"
        if "comment" in fname or ftype == "textarea":
            return "Testing comment input."
        if "date" in fname or ftype == "date":
            return "2025-01-01"
        if ftype in ("checkbox", "radio"):
            return "cb1"
        if ftype == "file":
            return "test_upload.txt"
        return "valid_value"

    lines = [header]
    for field in model["fields"]:
        fname = field["name"]
        val = infer_default_val(field)
        lines.append(f'    "{fname}": "{val}",')
    lines.append("}\n")

    # Helper function for test definition
    def add_test(func_name, intent, fields, expected, body_lines, doc_notes=""):
        lines.append(f'@pytest.mark.description(')
        lines.append(f'    intent="{intent}",')
        lines.append(f'    fields={fields!r},')
        lines.append(f'    expected="{expected}",')
        lines.append(f')')
        lines.append(f'def {func_name}():')
        lines.append(f'    """')
        lines.append(f'    Intent: {intent}')
        lines.append(f'    Target Field(s): {", ".join(fields)}')
        lines.append(f'    Expected Outcome: {expected}')
        if doc_notes:
            lines.append(f'    Notes: {doc_notes}')
        lines.append(f'    """')
        for b in body_lines:
            lines.append(f'    {b}')
        lines.append("")

    # 1. Required field validations
    for field in model["fields"]:
        fname = field["name"]
        conf = field.get("confidence", 1.0)
        source = field.get("source", spec_source)
        if field.get("required"):
            intent = f"Verify that '{fname}' is strictly required and rejecting blank submission."
            expected = "HTTP 400 with validation error when field is left blank"
            body = [
                f'payload = dict(VALID_PAYLOAD)',
                f'payload["{fname}"] = ""',
                f'r = {req_call}',
                f'assert r.status_code == 400, f"Expected 400 for empty {fname}, got {{r.status_code}}"',
            ]
            notes = f"Rule origin: {source} (confidence={conf})."
            if field.get("accessible_name"):
                notes += f" Mapped accessible element: '{field['accessible_name']}'."
            add_test(f"test_{fname}_required_enforced", intent, [fname], expected, body, notes)

    # 2. Field Boundary and Constraints validations (Case A: SRS / Backend Reference)
    for field in model["fields"]:
        fname = field["name"]
        ftype = field.get("type", "text")

        # Length bounds
        min_len = field.get("min_len")
        max_len = field.get("max_len")
        if min_len and min_len > 1:
            intent = f"Verify '{fname}' rejects inputs shorter than the minimum length of {min_len} characters."
            expected = f"HTTP 400 when length is {min_len - 1}"
            short_val = "a" * (min_len - 1)
            body = [
                f'payload = dict(VALID_PAYLOAD)',
                f'payload["{fname}"] = "{short_val}"',
                f'r = {req_call}',
                f'assert r.status_code == 400, f"Expected 400 for under-length {fname}, got {{r.status_code}}"',
            ]
            add_test(f"test_{fname}_min_length_boundary", intent, [fname], expected, body, f"SRS minimum length: {min_len}")

        if max_len:
            intent = f"Verify '{fname}' rejects inputs exceeding the maximum allowed length of {max_len} characters."
            expected = f"HTTP 400 when length exceeds {max_len}"
            long_val = "x" * (max_len + 5)
            body = [
                f'payload = dict(VALID_PAYLOAD)',
                f'payload["{fname}"] = "{long_val}"',
                f'r = {req_call}',
                f'assert r.status_code == 400, f"Expected 400 for over-length {fname}, got {{r.status_code}}"',
            ]
            add_test(f"test_{fname}_max_length_boundary", intent, [fname], expected, body, f"SRS maximum length: {max_len}")

        # Numeric bounds
        min_val = field.get("min")
        max_val = field.get("max")
        if min_val is not None:
            intent = f"Verify numeric field '{fname}' rejects values strictly below {min_val}."
            expected = f"HTTP 400 when value is {min_val - 1}"
            body = [
                f'payload = dict(VALID_PAYLOAD)',
                f'payload["{fname}"] = str({min_val - 1})',
                f'r = {req_call}',
                f'assert r.status_code == 400, f"Expected 400 for {fname} below {min_val}, got {{r.status_code}}"',
            ]
            add_test(f"test_{fname}_min_value_boundary", intent, [fname], expected, body, f"SRS minimum value: {min_val}")

        if max_val is not None:
            intent = f"Verify numeric field '{fname}' rejects values strictly above {max_val}."
            expected = f"HTTP 400 when value is {max_val + 1}"
            body = [
                f'payload = dict(VALID_PAYLOAD)',
                f'payload["{fname}"] = str({max_val + 1})',
                f'r = {req_call}',
                f'assert r.status_code == 400, f"Expected 400 for {fname} above {max_val}, got {{r.status_code}}"',
            ]
            add_test(f"test_{fname}_max_value_boundary", intent, [fname], expected, body, f"SRS maximum value: {max_val}")

        # Data format validation
        if ftype == "email":
            intent = f"Verify '{fname}' rejects malformed email addresses lacking domain/at-sign."
            expected = "HTTP 400 for invalid email format"
            body = [
                f'payload = dict(VALID_PAYLOAD)',
                f'payload["{fname}"] = "notanemailaddress"',
                f'r = {req_call}',
                f'assert r.status_code == 400, f"Expected 400 for invalid email, got {{r.status_code}}"',
            ]
            add_test(f"test_{fname}_invalid_email_format", intent, [fname], expected, body, "Format constraint validation")

        if ftype == "number":
            intent = f"Verify '{fname}' rejects non-numeric alphabetical strings."
            expected = "HTTP 400 when non-numeric string is provided"
            body = [
                f'payload = dict(VALID_PAYLOAD)',
                f'payload["{fname}"] = "not_a_number"',
                f'r = {req_call}',
                f'assert r.status_code == 400, f"Expected 400 for non-numeric {fname}, got {{r.status_code}}"',
            ]
            add_test(f"test_{fname}_non_numeric_rejected", intent, [fname], expected, body, "Type check validation")

    # 3. Black Box Accessibility Tree verification test (Case B)
    if case == "B":
        accessible_fields = [f["name"] for f in model["fields"] if f.get("accessible_name")]
        if accessible_fields:
            intent = "Verify that all accessible form fields mapped from the accessibility tree accept valid inputs."
            expected = "HTTP 200/201/success when all accessible controls are populated"
            body = [
                f"r = {req_valid_call}",
                "assert r.status_code in (200, 201, 204, 302, 303) or r.ok, f'Expected success status, got {r.status_code}'",
            ]
            add_test("test_accessibility_tree_contract", intent, accessible_fields, expected, body,
                     "Verified against Chromium accessibility tree hierarchy")

    # 4. Happy-path Acceptance validation
    all_fields = [f["name"] for f in model["fields"]]
    intent = "Sanity check that a fully compliant payload satisfying all form constraints is accepted."
    expected = "HTTP 200/201/success confirmation"
    body = [
        f"r = {req_valid_call}",
        "assert r.status_code in (200, 201, 204, 302, 303) or r.ok, f'Expected success status, got {r.status_code}'",
    ]
    add_test("test_full_valid_payload_accepted", intent, all_fields, expected, body,
             "Baseline happy-path contract validation")

    out_file = os.path.join(OUT_DIR, "test_contract.py")
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(out_file, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Generated {len(model['fields'])} field tests -> {out_file}")
    return out_file


if __name__ == "__main__":
    import sys
    gen(sys.argv[1] if len(sys.argv) > 1 else "A")
