"""AUTO-GENERATED by generator/gen_locustfile.py -- do not edit by hand.

Bypasses the UI entirely: POSTs straight to the backend form endpoint
(/submit), generating a fresh realistic payload per
request via Faker so load patterns look like real concurrent users
rather than one replayed payload.
"""
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "generator"))
from fake_data import fake_value_for  # noqa: E402

from locust import HttpUser, task, between

FIELDS = [{"name": "full_name", "type": "text"}, {"name": "email", "type": "email"}, {"name": "age", "type": "number"}, {"name": "password", "type": "password"}, {"name": "phone", "type": "text"}]


class FormUser(HttpUser):
    wait_time = between(0.5, 1.5)
    host = "http://127.0.0.1:5000"

    @task
    def submit_form(self):
        payload = {f["name"]: fake_value_for(f["name"], f["type"]) for f in FIELDS}
        self.client.post("/submit", data=payload)
