"""AUTO-GENERATED by generator/gen_playwright.py -- do not edit by hand.
Functional Browser UI Testing with Playwright.
Mode: Case B (black_box_accessibility_and_dom).
Target URL: https://testpages.eviltester.com/pages/forms/html-form/
"""
import os
import pytest
from playwright.sync_api import sync_playwright

URL = "https://testpages.eviltester.com/pages/forms/html-form/"
FIELD_VALUES = {
    "username": "JaneDoe",
    "password": "SecurePass123",
    "comments": "Automated functional test comment.",
    "filename": "JaneDoe",
    "checkboxes[]": "on",
    "radioval": "on",
    "multipleselect[]": "valid_text",
    "dropdown": "valid_text",
    "image": "25",
    "submitbutton": "valid_text",
    "reportmissingparams": "valid_text"
}
SCREENSHOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "results", "screenshots"))
os.makedirs(SCREENSHOT_DIR, exist_ok=True)


def _fill_form(page, values: dict):
    for name, val in values.items():
        # Try locator by name, id, or placeholder
        for sel in [f"[name='{name}']", f"#{name}"]:
            loc = page.locator(sel).first
            if loc.count() > 0:
                try:
                    tag = loc.evaluate("e => e.tagName.toLowerCase()")
                    itype = (loc.get_attribute("type") or "").lower()
                    if tag == "select":
                        opts = loc.locator("option").all()
                        if len(opts) > 1:
                            val_to_sel = opts[1].get_attribute("value") or opts[1].inner_text()
                            loc.select_option(val_to_sel)
                        elif opts:
                            loc.select_option(index=0)
                    elif itype in ("checkbox", "radio"):
                        loc.check()
                    elif itype == "file":
                        pass  # Skip file upload input
                    elif itype == "submit" or itype == "button":
                        pass
                    else:
                        loc.fill(str(val))
                except Exception:
                    pass
                break


def _click_submit(page):
    for sel in [
        "button[type='submit']",
        "input[type='submit']",
        "form button",
        "button:has-text('Submit')",
        "button:has-text('Register')",
        "button:has-text('Login')",
        "button",
    ]:
        loc = page.locator(sel).first
        if loc.count() > 0 and loc.is_visible():
            try:
                loc.click()
                return True
            except Exception:
                pass
    try:
        page.evaluate("() => { const f = document.querySelector('form'); if (f) f.requestSubmit(); }")
        return True
    except Exception:
        return False


@pytest.mark.description(
    intent="Functional browser submission: fill all discovered form fields and verify successful roundtrip.",
    fields=['username', 'password', 'comments', 'filename', 'checkboxes[]', 'checkboxes[]', 'checkboxes[]', 'radioval', 'radioval', 'radioval', 'multipleselect[]', 'dropdown', 'image', 'submitbutton', 'submitbutton', 'reportmissingparams'],
    expected="Form submits without page errors and updates UI or redirects to confirmation.",
)
def test_functional_form_submission():
    """
    Intent: Functional browser submission: fill all discovered form fields and verify successful roundtrip.
    Target Field(s): username, password, comments, filename, checkboxes[], checkboxes[], checkboxes[], radioval
    Expected Outcome: Form submits without page errors and updates UI or redirects to confirmation.
    """
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.goto(URL, timeout=20000, wait_until="domcontentloaded")
        initial_url = page.url

        _fill_form(page, FIELD_VALUES)
        submitted = _click_submit(page)
        assert submitted, "Failed to locate or click a submit control in the web form"

        # Wait for navigation or network settling
        try:
            page.wait_for_load_state("networkidle", timeout=3000)
        except Exception:
            pass

        # Check page health: ensure page didn't throw uncaught 500 error or blank white screen
        page_title = page.title()
        content = page.content()
        assert content and len(content) > 50, "Page content is unexpectedly empty after form submission"
        browser.close()
