"""AUTO-GENERATED by generator/gen_pytest.py -- do not edit by hand.
Phase 1: Unit Testing using Pytest.
Specification Mode: Case B (black_box_accessibility_and_dom).
Target URL: http://demo.owasp-juice.shop/
Method: POST
"""
import pytest
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

URL = "http://demo.owasp-juice.shop/"
session = requests.Session()
session.headers.update({"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"})
_adapter = HTTPAdapter(max_retries=Retry(total=3, backoff_factor=0.5, status_forcelist=[500, 502, 503, 504]))
session.mount("https://", _adapter)
session.mount("http://", _adapter)

VALID_PAYLOAD = {

}

@pytest.mark.description(
    intent="Sanity check that a fully compliant payload satisfying all form constraints is accepted.",
    fields=[],
    expected="HTTP 200/201/success confirmation",
)
def test_full_valid_payload_accepted():
    """
    Intent: Sanity check that a fully compliant payload satisfying all form constraints is accepted.
    Target Field(s): 
    Expected Outcome: HTTP 200/201/success confirmation
    Notes: Baseline happy-path contract validation
    """
    r = session.post(URL, data=VALID_PAYLOAD, timeout=10, allow_redirects=True)
    assert r.status_code in (200, 201, 204, 302, 303) or r.ok, f'Expected success status, got {r.status_code}'
