"""AUTO-GENERATED by generator/gen_pytest.py -- do not edit by hand.
Phase 1: Unit Testing using Pytest.
Specification Mode: Case B (black_box_accessibility_and_dom).
Target URL: http://127.0.0.1:5000/buggy-submit
Method: POST
"""
import pytest
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

URL = "http://127.0.0.1:5000/buggy-submit"
session = requests.Session()
session.headers.update({"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"})
_adapter = HTTPAdapter(max_retries=Retry(total=3, backoff_factor=0.5, status_forcelist=[500, 502, 503, 504]))
session.mount("https://", _adapter)
session.mount("http://", _adapter)

VALID_PAYLOAD = {

    "username": "JaneDoe",
    "email": "jane.doe@example.com",
    "age": "25",
    "password": "SecurePass123",
}

@pytest.mark.description(
    intent="Verify that 'username' is strictly required and rejecting blank submission.",
    fields=['username'],
    expected="HTTP 400 with validation error when field is left blank",
)
def test_username_required_enforced():
    """
    Intent: Verify that 'username' is strictly required and rejecting blank submission.
    Target Field(s): username
    Expected Outcome: HTTP 400 with validation error when field is left blank
    Notes: Rule origin: black_box_accessibility_tree_and_dom (confidence=0.65). Mapped accessible element: 'Username (Required)'.
    """
    payload = dict(VALID_PAYLOAD)
    payload["username"] = ""
    r = session.post(URL, data=payload, timeout=10, allow_redirects=True)
    assert r.status_code == 400, f"Expected 400 for empty username, got {r.status_code}"

@pytest.mark.description(
    intent="Verify that 'email' is strictly required and rejecting blank submission.",
    fields=['email'],
    expected="HTTP 400 with validation error when field is left blank",
)
def test_email_required_enforced():
    """
    Intent: Verify that 'email' is strictly required and rejecting blank submission.
    Target Field(s): email
    Expected Outcome: HTTP 400 with validation error when field is left blank
    Notes: Rule origin: black_box_accessibility_tree_and_dom (confidence=0.65). Mapped accessible element: 'Email Address (Required)'.
    """
    payload = dict(VALID_PAYLOAD)
    payload["email"] = ""
    r = session.post(URL, data=payload, timeout=10, allow_redirects=True)
    assert r.status_code == 400, f"Expected 400 for empty email, got {r.status_code}"

@pytest.mark.description(
    intent="Verify that 'age' is strictly required and rejecting blank submission.",
    fields=['age'],
    expected="HTTP 400 with validation error when field is left blank",
)
def test_age_required_enforced():
    """
    Intent: Verify that 'age' is strictly required and rejecting blank submission.
    Target Field(s): age
    Expected Outcome: HTTP 400 with validation error when field is left blank
    Notes: Rule origin: black_box_accessibility_tree_and_dom (confidence=0.65). Mapped accessible element: 'Age (Declared Min: 18, Max: 100)'.
    """
    payload = dict(VALID_PAYLOAD)
    payload["age"] = ""
    r = session.post(URL, data=payload, timeout=10, allow_redirects=True)
    assert r.status_code == 400, f"Expected 400 for empty age, got {r.status_code}"

@pytest.mark.description(
    intent="Verify that 'password' is strictly required and rejecting blank submission.",
    fields=['password'],
    expected="HTTP 400 with validation error when field is left blank",
)
def test_password_required_enforced():
    """
    Intent: Verify that 'password' is strictly required and rejecting blank submission.
    Target Field(s): password
    Expected Outcome: HTTP 400 with validation error when field is left blank
    Notes: Rule origin: black_box_accessibility_tree_and_dom (confidence=0.65). Mapped accessible element: 'Password (Required, Min 8 chars)'.
    """
    payload = dict(VALID_PAYLOAD)
    payload["password"] = ""
    r = session.post(URL, data=payload, timeout=10, allow_redirects=True)
    assert r.status_code == 400, f"Expected 400 for empty password, got {r.status_code}"

@pytest.mark.description(
    intent="Verify 'email' rejects malformed email addresses lacking domain/at-sign.",
    fields=['email'],
    expected="HTTP 400 for invalid email format",
)
def test_email_invalid_email_format():
    """
    Intent: Verify 'email' rejects malformed email addresses lacking domain/at-sign.
    Target Field(s): email
    Expected Outcome: HTTP 400 for invalid email format
    Notes: Format constraint validation
    """
    payload = dict(VALID_PAYLOAD)
    payload["email"] = "notanemailaddress"
    r = session.post(URL, data=payload, timeout=10, allow_redirects=True)
    assert r.status_code == 400, f"Expected 400 for invalid email, got {r.status_code}"

@pytest.mark.description(
    intent="Verify 'age' rejects non-numeric alphabetical strings.",
    fields=['age'],
    expected="HTTP 400 when non-numeric string is provided",
)
def test_age_non_numeric_rejected():
    """
    Intent: Verify 'age' rejects non-numeric alphabetical strings.
    Target Field(s): age
    Expected Outcome: HTTP 400 when non-numeric string is provided
    Notes: Type check validation
    """
    payload = dict(VALID_PAYLOAD)
    payload["age"] = "not_a_number"
    r = session.post(URL, data=payload, timeout=10, allow_redirects=True)
    assert r.status_code == 400, f"Expected 400 for non-numeric age, got {r.status_code}"

@pytest.mark.description(
    intent="Verify that all accessible form fields mapped from the accessibility tree accept valid inputs.",
    fields=['username', 'email', 'age', 'password'],
    expected="HTTP 200/201/success when all accessible controls are populated",
)
def test_accessibility_tree_contract():
    """
    Intent: Verify that all accessible form fields mapped from the accessibility tree accept valid inputs.
    Target Field(s): username, email, age, password
    Expected Outcome: HTTP 200/201/success when all accessible controls are populated
    Notes: Verified against Chromium accessibility tree hierarchy
    """
    r = session.post(URL, data=VALID_PAYLOAD, timeout=10, allow_redirects=True)
    assert r.status_code in (200, 201, 204, 302, 303) or r.ok, f'Expected success status, got {r.status_code}'

@pytest.mark.description(
    intent="Sanity check that a fully compliant payload satisfying all form constraints is accepted.",
    fields=['username', 'email', 'age', 'password'],
    expected="HTTP 200/201/success confirmation",
)
def test_full_valid_payload_accepted():
    """
    Intent: Sanity check that a fully compliant payload satisfying all form constraints is accepted.
    Target Field(s): username, email, age, password
    Expected Outcome: HTTP 200/201/success confirmation
    Notes: Baseline happy-path contract validation
    """
    r = session.post(URL, data=VALID_PAYLOAD, timeout=10, allow_redirects=True)
    assert r.status_code in (200, 201, 204, 302, 303) or r.ok, f'Expected success status, got {r.status_code}'
