"""AUTO-GENERATED by generator/gen_pytest.py -- do not edit by hand.
Phase 1: Unit Testing using Pytest.
Specification Mode: Case B (black_box_accessibility_and_dom).
Target URL: https://testpages.eviltester.com/pages/forms/html-form/submit
Method: POST
"""
import pytest
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry

URL = "https://testpages.eviltester.com/pages/forms/html-form/submit"
session = requests.Session()
session.headers.update({"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"})
_adapter = HTTPAdapter(max_retries=Retry(total=3, backoff_factor=0.5, status_forcelist=[500, 502, 503, 504]))
session.mount("https://", _adapter)
session.mount("http://", _adapter)

VALID_PAYLOAD = {

    "username": "JaneDoe",
    "password": "SecurePass123",
    "comments": "Testing comment input.",
    "filename": "JaneDoe",
    "checkboxes[]": "cb1",
    "checkboxes[]": "cb1",
    "checkboxes[]": "cb1",
    "radioval": "cb1",
    "radioval": "cb1",
    "radioval": "cb1",
    "multipleselect[]": "valid_value",
    "dropdown": "valid_value",
    "image": "25",
    "submitbutton": "valid_value",
    "submitbutton": "valid_value",
    "reportmissingparams": "valid_value",
}

@pytest.mark.description(
    intent="Sanity check that a fully compliant payload satisfying all form constraints is accepted.",
    fields=['username', 'password', 'comments', 'filename', 'checkboxes[]', 'checkboxes[]', 'checkboxes[]', 'radioval', 'radioval', 'radioval', 'multipleselect[]', 'dropdown', 'image', 'submitbutton', 'submitbutton', 'reportmissingparams'],
    expected="HTTP 200/201/success confirmation",
)
def test_full_valid_payload_accepted():
    """
    Intent: Sanity check that a fully compliant payload satisfying all form constraints is accepted.
    Target Field(s): username, password, comments, filename, checkboxes[], checkboxes[], checkboxes[], radioval, radioval, radioval, multipleselect[], dropdown, image, submitbutton, submitbutton, reportmissingparams
    Expected Outcome: HTTP 200/201/success confirmation
    Notes: Baseline happy-path contract validation
    """
    r = session.post(URL, data=VALID_PAYLOAD, timeout=10, allow_redirects=True)
    assert r.status_code in (200, 201, 204, 302, 303) or r.ok, f'Expected success status, got {r.status_code}'
