"""AUTO-GENERATED by generator/gen_playwright.py -- do not edit by hand.
Functional Browser UI Testing with Playwright.
Mode: Case B (black_box_accessibility_and_dom).
Target URL: http://127.0.0.1:5000/buggy-form
"""
import os
import pytest
from playwright.sync_api import sync_playwright

URL = "http://127.0.0.1:5000/buggy-form"
FIELD_VALUES = {
    "username": "JaneDoe",
    "email": "jane.doe@example.com",
    "age": "25",
    "password": "SecurePass123"
}
SCREENSHOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "results", "screenshots"))
os.makedirs(SCREENSHOT_DIR, exist_ok=True)


def _fill_form(page, values: dict):
    for name, val in values.items():
        # Try locator by name, id, or placeholder
        for sel in [f"[name='{name}']", f"#{name}"]:
            loc = page.locator(sel).first
            if loc.count() > 0:
                try:
                    tag = loc.evaluate("e => e.tagName.toLowerCase()")
                    itype = (loc.get_attribute("type") or "").lower()
                    if tag == "select":
                        opts = loc.locator("option").all()
                        if len(opts) > 1:
                            val_to_sel = opts[1].get_attribute("value") or opts[1].inner_text()
                            loc.select_option(val_to_sel)
                        elif opts:
                            loc.select_option(index=0)
                    elif itype in ("checkbox", "radio"):
                        loc.check()
                    elif itype == "file":
                        pass  # Skip file upload input
                    elif itype == "submit" or itype == "button":
                        pass
                    else:
                        loc.fill(str(val))
                except Exception:
                    pass
                break


def _click_submit(page):
    for sel in [
        "button[type='submit']",
        "input[type='submit']",
        "form button",
        "button:has-text('Submit')",
        "button:has-text('Register')",
        "button:has-text('Login')",
        "button",
    ]:
        loc = page.locator(sel).first
        if loc.count() > 0 and loc.is_visible():
            try:
                loc.click()
                return True
            except Exception:
                pass
    try:
        page.evaluate("() => { const f = document.querySelector('form'); if (f) f.requestSubmit(); }")
        return True
    except Exception:
        return False


@pytest.mark.description(
    intent="Functional browser submission: fill all discovered form fields and verify successful roundtrip.",
    fields=['username', 'email', 'age', 'password'],
    expected="Form submits without page errors and updates UI or redirects to confirmation.",
)
def test_functional_form_submission():
    """
    Intent: Functional browser submission: fill all discovered form fields and verify successful roundtrip.
    Target Field(s): username, email, age, password
    Expected Outcome: Form submits without page errors and updates UI or redirects to confirmation.
    """
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.goto(URL, timeout=20000, wait_until="domcontentloaded")
        initial_url = page.url

        _fill_form(page, FIELD_VALUES)
        submitted = _click_submit(page)
        assert submitted, "Failed to locate or click a submit control in the web form"

        # Wait for navigation or network settling
        try:
            page.wait_for_load_state("networkidle", timeout=3000)
        except Exception:
            pass

        # Check page health: ensure page didn't throw uncaught 500 error or blank white screen
        page_title = page.title()
        content = page.content()
        assert content and len(content) > 50, "Page content is unexpectedly empty after form submission"
        browser.close()


@pytest.mark.description(
    intent="Client-side functional check: submitting with blank 'username' is blocked by browser validation.",
    fields='username',
    expected="Field triggers HTML5 validity.valueMissing or form submission is blocked.",
)
def test_functional_client_required_username():
    """
    Intent: Client-side functional check: submitting with blank 'username' is blocked by browser validation.
    Target Field(s): username
    Expected Outcome: Field triggers HTML5 validity.valueMissing or form submission is blocked.
    """
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.goto(URL, timeout=20000, wait_until="domcontentloaded")

        # Fill all fields EXCEPT the required field
        test_payload = dict(FIELD_VALUES)
        test_payload["username"] = ""
        _fill_form(page, test_payload)

        _click_submit(page)
        try:
            page.wait_for_timeout(500)
        except Exception:
            pass

        # Check validity on the required element
        val_missing = page.eval_on_selector(
            "[name='username'], #username",
            "el => el.validity ? el.validity.valueMissing : false"
        )
        assert val_missing or page.url == URL, f"Browser did not flag missing required field 'username'"
        browser.close()


@pytest.mark.description(
    intent="Client-side functional check: submitting with blank 'email' is blocked by browser validation.",
    fields='email',
    expected="Field triggers HTML5 validity.valueMissing or form submission is blocked.",
)
def test_functional_client_required_email():
    """
    Intent: Client-side functional check: submitting with blank 'email' is blocked by browser validation.
    Target Field(s): email
    Expected Outcome: Field triggers HTML5 validity.valueMissing or form submission is blocked.
    """
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.goto(URL, timeout=20000, wait_until="domcontentloaded")

        # Fill all fields EXCEPT the required field
        test_payload = dict(FIELD_VALUES)
        test_payload["email"] = ""
        _fill_form(page, test_payload)

        _click_submit(page)
        try:
            page.wait_for_timeout(500)
        except Exception:
            pass

        # Check validity on the required element
        val_missing = page.eval_on_selector(
            "[name='email'], #email",
            "el => el.validity ? el.validity.valueMissing : false"
        )
        assert val_missing or page.url == URL, f"Browser did not flag missing required field 'email'"
        browser.close()


@pytest.mark.description(
    intent="Client-side functional check: submitting with blank 'age' is blocked by browser validation.",
    fields='age',
    expected="Field triggers HTML5 validity.valueMissing or form submission is blocked.",
)
def test_functional_client_required_age():
    """
    Intent: Client-side functional check: submitting with blank 'age' is blocked by browser validation.
    Target Field(s): age
    Expected Outcome: Field triggers HTML5 validity.valueMissing or form submission is blocked.
    """
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.goto(URL, timeout=20000, wait_until="domcontentloaded")

        # Fill all fields EXCEPT the required field
        test_payload = dict(FIELD_VALUES)
        test_payload["age"] = ""
        _fill_form(page, test_payload)

        _click_submit(page)
        try:
            page.wait_for_timeout(500)
        except Exception:
            pass

        # Check validity on the required element
        val_missing = page.eval_on_selector(
            "[name='age'], #age",
            "el => el.validity ? el.validity.valueMissing : false"
        )
        assert val_missing or page.url == URL, f"Browser did not flag missing required field 'age'"
        browser.close()


@pytest.mark.description(
    intent="Client-side functional check: submitting with blank 'password' is blocked by browser validation.",
    fields='password',
    expected="Field triggers HTML5 validity.valueMissing or form submission is blocked.",
)
def test_functional_client_required_password():
    """
    Intent: Client-side functional check: submitting with blank 'password' is blocked by browser validation.
    Target Field(s): password
    Expected Outcome: Field triggers HTML5 validity.valueMissing or form submission is blocked.
    """
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        page = browser.new_page()
        page.goto(URL, timeout=20000, wait_until="domcontentloaded")

        # Fill all fields EXCEPT the required field
        test_payload = dict(FIELD_VALUES)
        test_payload["password"] = ""
        _fill_form(page, test_payload)

        _click_submit(page)
        try:
            page.wait_for_timeout(500)
        except Exception:
            pass

        # Check validity on the required element
        val_missing = page.eval_on_selector(
            "[name='password'], #password",
            "el => el.validity ? el.validity.valueMissing : false"
        )
        assert val_missing or page.url == URL, f"Browser did not flag missing required field 'password'"
        browser.close()
