"""AUTO-GENERATED by generator/gen_playwright.py -- do not edit by hand."""
import json
import os
from playwright.sync_api import sync_playwright

URL = "http://127.0.0.1:5000/"
SCREENSHOT_DIR = os.path.join("..", "results", "screenshots")
os.makedirs(SCREENSHOT_DIR, exist_ok=True)
results = []

def record(name, passed, detail='', screenshot=None):
    results.append({'test': name, 'passed': passed, 'detail': detail, 'screenshot': screenshot})

def snap(page, name):
    """Capture a screenshot on failure -- gives a test-level drill-down
    artifact instead of just a pass/fail line, the way Playwright's own
    HTML reporter and most CI dashboards do."""
    path = os.path.join(SCREENSHOT_DIR, f'{name}.png')
    try:
        page.screenshot(path=path)
        return f'results/screenshots/{name}.png'
    except Exception:
        return None

def run():
    with sync_playwright() as p:
        browser = p.chromium.launch(channel="chrome", headless=True)
        page = browser.new_page()

        # --- Positive case: all valid values ---
        page.goto(URL)
        page.evaluate("document.querySelector('form').noValidate = true")
        page.fill("input[name='full_name']", "Jane Doe")
        page.fill("input[name='email']", "jane.doe@example.com")
        page.fill("input[name='age']", "25")
        page.fill("input[name='password']", "SecurePass1")
        page.fill("input[name='phone']", "9876543210")
        page.click("button[type='submit']")
        page.wait_for_selector("#result .ok, #result .err", timeout=5000)
        ok = page.query_selector("#result .ok") is not None
        record("positive_all_valid", ok, screenshot=(None if ok else snap(page, "positive_all_valid")))

        # --- Negative cases: one invalid field at a time ---
        page.goto(URL)
        page.evaluate("document.querySelector('form').noValidate = true")
        page.fill("input[name='full_name']", "")
        page.fill("input[name='email']", "jane.doe@example.com")
        page.fill("input[name='age']", "25")
        page.fill("input[name='password']", "SecurePass1")
        page.fill("input[name='phone']", "9876543210")
        page.click("button[type='submit']")
        page.wait_for_selector("#result .ok, #result .err", timeout=5000)
        rejected = page.query_selector("#result .err") is not None
        name = "negative_full_name_invalid"
        record(name, rejected, screenshot=(None if rejected else snap(page, name)))

        page.goto(URL)
        page.evaluate("document.querySelector('form').noValidate = true")
        page.fill("input[name='full_name']", "Jane Doe")
        page.fill("input[name='email']", "not-an-email")
        page.fill("input[name='age']", "25")
        page.fill("input[name='password']", "SecurePass1")
        page.fill("input[name='phone']", "9876543210")
        page.click("button[type='submit']")
        page.wait_for_selector("#result .ok, #result .err", timeout=5000)
        rejected = page.query_selector("#result .err") is not None
        name = "negative_email_invalid"
        record(name, rejected, screenshot=(None if rejected else snap(page, name)))

        page.goto(URL)
        page.evaluate("document.querySelector('form').noValidate = true")
        page.fill("input[name='full_name']", "Jane Doe")
        page.fill("input[name='email']", "jane.doe@example.com")
        page.fill("input[name='age']", "5")
        page.fill("input[name='password']", "SecurePass1")
        page.fill("input[name='phone']", "9876543210")
        page.click("button[type='submit']")
        page.wait_for_selector("#result .ok, #result .err", timeout=5000)
        rejected = page.query_selector("#result .err") is not None
        name = "negative_age_invalid"
        record(name, rejected, screenshot=(None if rejected else snap(page, name)))

        page.goto(URL)
        page.evaluate("document.querySelector('form').noValidate = true")
        page.fill("input[name='full_name']", "Jane Doe")
        page.fill("input[name='email']", "jane.doe@example.com")
        page.fill("input[name='age']", "25")
        page.fill("input[name='password']", "short")
        page.fill("input[name='phone']", "9876543210")
        page.click("button[type='submit']")
        page.wait_for_selector("#result .ok, #result .err", timeout=5000)
        rejected = page.query_selector("#result .err") is not None
        name = "negative_password_invalid"
        record(name, rejected, screenshot=(None if rejected else snap(page, name)))

        browser.close()

    with open("../results/playwright_results.json", "w", encoding="utf-8") as f:
        json.dump(results, f, indent=2)
    print(f"Playwright: {sum(r['passed'] for r in results)}/{len(results)} passed")

if __name__ == "__main__":
    run()