"""
Generates a pytest test SKELETON from a plain-English prompt, e.g.
"test that age below 18 is rejected" or "check email format validation".

Tries the LLM wrapper first (with the current feature model as context,
so it knows real field names). Falls back to a rule-based generator that
keyword-matches the prompt against the feature model's field names and
templates a skeleton test -- this keeps the feature usable offline/without
an API key, at the cost of being less flexible than a real LLM.

Generated files are written for the developer to REVIEW, not auto-run:
they land in tests_generated/custom/ and are never picked up by
run_all.py's own pytest invocation (which only runs test_contract.py).
"""
import os
import re
import json
from ai_wrapper.llm_client import complete

ROOT = os.path.join(os.path.dirname(__file__), "..")
CUSTOM_DIR = os.path.join(ROOT, "tests_generated", "custom")

LLM_PROMPT_TEMPLATE = """Write ONE Python pytest test function (not a class) that
tests a web form's backend by POSTing to {endpoint} with the `requests` library.

Known form fields (name: type, required): {fields_desc}
A valid baseline payload dict called VALID_PAYLOAD already exists with correct
values for every field -- reuse `dict(VALID_PAYLOAD)` and override only the
field(s) relevant to this test.

User's request: "{user_prompt}"

Output ONLY the Python function code (with a docstring explaining intent),
no explanation, no markdown fences, no imports."""


def _guess_target_field(prompt: str, field_names: list) -> str | None:
    prompt_lower = prompt.lower()
    for name in field_names:
        if name.lower() in prompt_lower or name.replace("_", " ") in prompt_lower:
            return name
    return None


def _rule_based_skeleton(prompt: str, model: dict) -> str:
    field_names = [f["name"] for f in model["fields"]]
    target = _guess_target_field(prompt, field_names) or (field_names[0] if field_names else "field")
    expect_reject = any(w in prompt.lower() for w in
                         ["reject", "invalid", "fail", "error", "below", "missing", "empty", "not accept"])
    expect_accept = any(w in prompt.lower() for w in ["accept", "valid", "success", "allow"])

    func_name = "test_custom_" + re.sub(r"[^a-z0-9]+", "_", prompt.lower()).strip("_")[:50]
    assertion = "== 400" if (expect_reject and not expect_accept) else "== 200"
    probe_value = '""' if expect_reject else '"valid_value"'

    return f'''def {func_name}():
    """Auto-generated (rule-based fallback) from the prompt:
    "{prompt}"

    Target field guessed: {target}
    Expected outcome: request should return {assertion.strip("= ")}.
    NOTE: this is a template -- review/edit the probe value below before
    relying on this test; the rule-based generator cannot infer exact
    valid/invalid values as well as a real LLM or the extraction pipeline can.
    """
    payload = dict(VALID_PAYLOAD)
    payload["{target}"] = {probe_value}
    r = requests.post(URL, data=payload, timeout=5)
    assert r.status_code {assertion}
'''


def generate_skeleton(user_prompt: str, feature_model: dict) -> dict:
    fields_desc = ", ".join(
        f'{f["name"]} ({f.get("type","text")}, required={f.get("required", False)})'
        for f in feature_model["fields"]
    )
    llm_prompt = LLM_PROMPT_TEMPLATE.format(
        endpoint=feature_model.get("submit_endpoint", "/submit"),
        fields_desc=fields_desc,
        user_prompt=user_prompt,
    )
    llm_result = complete(llm_prompt)
    if llm_result:
        code = llm_result.strip().strip("`")
        if code.startswith("python"):
            code = code[len("python"):].lstrip()
        return {"code": code, "source": "llm"}
    return {"code": _rule_based_skeleton(user_prompt, feature_model), "source": "rule_based"}


def save_skeleton(user_prompt: str, feature_model: dict) -> str:
    os.makedirs(CUSTOM_DIR, exist_ok=True)
    result = generate_skeleton(user_prompt, feature_model)
    slug = re.sub(r"[^a-z0-9]+", "_", user_prompt.lower()).strip("_")[:40]
    filename = f"test_custom_{slug}.py"
    path = os.path.join(CUSTOM_DIR, filename)

    base_url = "http://127.0.0.1:5000"
    try:
        with open(os.path.join(ROOT, "config.json"), encoding="utf-8") as cf:
            base_url = json.load(cf).get("target_url", base_url).rstrip("/")
    except Exception:
        pass
    full_url = base_url + feature_model.get("submit_endpoint", "/submit")

    header = (
        f'"""Generated by ai_wrapper/test_generator.py (source: {result["source"]})\n'
        f'Prompt: "{user_prompt}"\n'
        f'Review before use -- not auto-executed by run_all.py.\n"""\n'
        f"import requests\n\n"
        f'URL = "{full_url}"\n\n'
    )
    with open(path, "w", encoding="utf-8") as f:
        f.write(header + result["code"])
    return path
